# config/packages/acseo_typesense.yaml
acseo_typesense:
    # Typesense host settings
    typesense:
        url: '%env(resolve:TYPESENSE_URL)%'
        key: '%env(resolve:TYPESENSE_KEY)%'
    # Collection settings
    collections:
        product:                                     # Typesense collection name
            entity: 'App\Entity\Product'              # Doctrine Entity class
            fields: 
                #
                # Keeping Database and Typesense synchronized with ids
                #
                id:                                # Entity attribute name
                    name: id                       # Typesense attribute name
                    type: primary                  # Attribute type
                #
                # Using again id as a sortable field (int32 required)
                #
                sortable_id:
                    entity_attribute: id             # Entity attribute name forced
                    name: sortable_id                # Typesense field name
                    type: int32
                product_name:
                    name: product_name
                    type: string
                product_description:
                     name: product_description
                     type: object                    # Object conversion with __toString()
            default_sorting_field: sortable_id       # Default sorting field. Must be int32 or float