sonata_seo:
  encoding: UTF-8
  page:
    title: "scoops feraga"
    #title_prefix:  'Prefix |'
    title_suffix: " | scoops feraga"
    default: sonata.seo.page.default
    metas:
      name:
        keywords: scoops feraga, cameroun, ferme intégée, agriculture, élévage

        robots: index, follow

      property:
        # Facebook application settings
        "fb:app_id": "389898079878693"
        "fb:admins": Emmanuel Ngue

        # Open Graph information
        # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
        "og:site_name": scoops feraga

      http-equiv:
        "Content-Type": text/html; charset=utf-8
        #'X-Ua-Compatible':      IE=EmulateIE7

      charset:
        UTF-8: ""

    head:
      "xmlns": http://www.w3.org/1999/xhtml
      "xmlns:og": http://opengraphprotocol.org/schema/
      #'xmlns:fb':           "http://www.facebook.com/2008/fbml"
