twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        ProductCategories: '@App\Twig\ExtensionTwig'

when@test:
    twig:
        strict_variables: true
        form_themes: ["bootstrap_4_layout.html.twig"]
