#index:
#    path: /
#    controller: App\Controller\DefaultController::index

connect_facebook_check:
  path: /oauth/check/{service}
  controller: Symfony\Bundle\FramewordBundle\Controller\TemplateController

connect_google_check:
  path: /connect/google/check
  controller: Symfony\Bundle\FramewordBundle\Controller\TemplateController
